---
title: "{{folder_name}}"
subtitle: "Analysis"
date: "`r Sys.Date()`"
execute: 
  echo: true
format:
  html:
    page-layout: full
    theme: united
    toc: true
    toc-float: true
    toc-depth: 2
    toc-location: left
embed-resources: true
---

```{r setup}
#| include: false
set.seed({{format(Sys.Date(), format = "%Y%m%d")}})
options(openxlsx.dateFormat = "yyyy-mm-dd")
```

# Analytic Data Import

```{r import}
library(dsverse); library(tidyverse)

# setting MSK ggplot theme, gtsummary theme, and color palette
theme_set(mskRvis::theme_biostat()); theme_gtsummary_pcctc(); mskRvis::set_msk_palette()

# importing master analytic data set
load(file = here_data("derived-data", "raw-data-cleaned.Rdata"))
```


# Analysis

```{r analysis1}

```

# Save Results

```{r save}
# list result objects here. save only those needed for the final report
save(
  df_results, gt_table1,
  file = here_data("results", "results.Rdata")
) |> 
  sp_upload_file()
```

::: {style="font-size: 75%;"}
Data Cut Date: `r get_data_date()`
:::
