---
title: "{{folder_name}}"
date: "`r format(Sys.Date(), format='%B %d, %Y')`"
format:
  html:
    page-layout: full
    theme: united
    mainfont: 'Open Sans'
    linkcolor: '#0000EE'
    toc: true
    toc-float: true
    toc-depth: 2
    toc-location: left
  docx:
    reference-doc: templates/doc_template.docx
embed-resources: true
execute:
  echo: false
  warning: false
  message: false
bibliography: templates/references.bib
csl: templates/european-urology.csl
---

```{r setup}
#| include: false
# set chunk defaults, code chunks are NOT printed in output for report
set.seed({{format(Sys.Date(), format = "%Y%m%d")}})
options(subdir_name = "{{getOption('croquet.name')}}", openxlsx.dateFormat = "yyyy-mm-dd")
```

```{r import}
#| include: false
library(dsverse); library(tidyverse)
# setting MSK ggplot theme, gtsummary theme, and color palette
theme_set(mskRvis::theme_biostat()); theme_gtsummary_pcctc(); mskRvis::set_msk_palette()

# Import analysis result objects here
load(here_data("results", "results.Rdata"))
```

```{r inline_text}
#| include: false

# define complex inline-reporting objects here
```

# Methods

Describe cohort and analytic methods here.

All analyses were conducted using `r cite_r(pkgs = c("gtsummary", "tidyverse"), add_citation = TRUE)`.

# Results

Describe analytic results here.

# Tables & Figures


# References
