---
title: "{{folder_name}}"
subtitle: "Initial Setup"
date: "`r Sys.Date()`"
format:
  html:
    page-layout: full
    theme: united
    toc: true
    toc-float: true
    toc-depth: 2
    toc-location: left
embed-resources: true
execute: 
  echo: true
---

```{r setup}
#| include: false
set.seed({{format(Sys.Date(), format = "%Y%m%d")}})
options(openxlsx.dateFormat = "yyyy-mm-dd")
```

# Raw Data Import

```{r import}
library(dsverse); library(tidyverse)

# setting MSK ggplot theme, gtsummary theme, and color palette
theme_set(mskRvis::theme_biostat()); theme_gtsummary_pcctc(); mskRvis::set_msk_palette()

# example code for importing excel file
df_raw_data <-
  readxl::read_excel(
    path = here_data("Raw Data from PI.xlsx")
  ) %>%
  janitor::clean_names(case = "all_caps") %>% # uppercase col names
  mutate(across(where(is.POSIXt), as_date)) # use lubridates
```

# Create Master Analytic Data Set

```{r cleaning}

```


# Check Variable Derivations

```{r checking}

```

# Save Analytic Data

```{r save}
# applying variable labels, and dropping raw variables
df_main <- df_main %>%
  set_derived_variable_labels(path = "{{do.call(here::here, list(getOption(\"croquet.name\"), stringr::str_glue(\"derived-variables_{sub('^\\\\d{2}-', '', getOption('croquet.name'))}.xlsx\")) |> purrr::discard(rlang::is_empty))}}")

# overview of master analytic dataset
skimr::skim(df_main)

#saving master analytic data set
save(df_main, here_data("derived-data", "raw-data-cleaned.Rdata"))
```

::: {style="font-size: 75%;"}
Data Cut Date: `r croquet::get_data_date()`
:::
